export const SET_PESQUISA = 'SET_PESQUISA';
export const RESET_PESQUISA = 'RESET_PESQUISA';

export const SET_PESQUISA_DETALHADA = 'SET_PESQUISA_DETALHADA';
export const RESET_PESQUISA_DETALHADA = 'RESET_PESQUISA_DETALHADA';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SET_LOADING = 'SET_LOADING';